source("cost_side/robustness_helpers.R")

out_dir <- ensure_outputs_dir()
panel <- load_cost_panel("cost_side_panel.csv")
df <- build_regression_frame(panel, include_elasticities = FALSE) %>%
  filter(!is.na(pcOth1_pct1_lag1))

country_counts <- df %>%
  filter(!is.na(pcOth1_code1), pcOth1_code1 != "") %>%
  count(pcOth1_code1, name = "baseline_rows", sort = TRUE)

omissions <- c("None", country_counts$pcOth1_code1)

country_slug <- function(country) {
  slug <- tolower(gsub("[^[:alnum:]]+", "_", country))
  gsub("^_|_$", "", slug)
}

fit_spec <- function(data) {
  feols(
    ln_costs ~ ln_inv_rer_code1:pcOth1_pct1_lag1 +
      ln_size + ln_weight + ln_hp + ln_mpg | make_model + year,
    data = data,
    cluster = ~ make_model
  )
}

fit_fd_spec <- function(data) {
  fd <- build_fd_frame(data, keep_cols = c("pcOth1_pct1_lag1"))
  feols(
    ln_costs ~ ln_inv_rer_code1:pcOth1_pct1_lag1 +
      ln_size + ln_weight + ln_hp + ln_mpg | year,
    data = fd,
    cluster = ~ make_model
  )
}

coef_rows <- list()
sample_rows <- list()

for (country in omissions) {
  spec_name <- if (country == "None") "full_sample" else paste0("drop_", country_slug(country))
  sample_df <- if (country == "None") {
    df
  } else {
    df %>% filter(pcOth1_code1 != country)
  }

  model_levels <- fit_spec(sample_df)
  model_fd <- fit_fd_spec(sample_df)

  coef_rows[[length(coef_rows) + 1L]] <- extract_term_row(
    model_levels,
    "ln_inv_rer_code1:pcOth1_pct1_lag1",
    spec_name,
    "levels"
  ) %>%
    mutate(omitted_country = country)

  coef_rows[[length(coef_rows) + 1L]] <- extract_term_row(
    model_fd,
    "ln_inv_rer_code1:pcOth1_pct1_lag1",
    spec_name,
    "fd"
  ) %>%
    mutate(omitted_country = country)

  sample_rows[[length(sample_rows) + 1L]] <- data.frame(
    spec = spec_name,
    omitted_country = country,
    rows = nrow(sample_df),
    make_models = dplyr::n_distinct(sample_df$make_model),
    baseline_country_rows = if (country == "None") nrow(df) else sum(df$pcOth1_code1 == country, na.rm = TRUE),
    omitted_rows = if (country == "None") 0L else sum(df$pcOth1_code1 == country, na.rm = TRUE),
    omitted_make_models = if (country == "None") 0L else dplyr::n_distinct(df$make_model[df$pcOth1_code1 == country]),
    stringsAsFactors = FALSE
  )
}

coef_df <- bind_rows(coef_rows)
sample_df <- bind_rows(sample_rows)

write.csv(
  coef_df,
  file.path(out_dir, "leave_one_country_out_coefficients.csv"),
  row.names = FALSE
)
write.csv(
  sample_df,
  file.path(out_dir, "leave_one_country_out_sample_counts.csv"),
  row.names = FALSE
)

plot_df <- coef_df %>%
  filter(spec == "levels") %>%
  mutate(
    lower = estimate - 1.96 * std_error,
    upper = estimate + 1.96 * std_error,
    label = if_else(omitted_country == "None", "Full sample", paste("Drop", omitted_country))
  )

png(
  filename = file.path(out_dir, "leave_one_country_out_eta.png"),
  width = 1000,
  height = max(650, 120 + 55 * nrow(plot_df)),
  res = 120
)
par(mar = c(5, 10, 4, 2))
plot(
  plot_df$estimate,
  seq_len(nrow(plot_df)),
  xlim = range(c(plot_df$lower, plot_df$upper)),
  ylim = c(0.5, nrow(plot_df) + 0.5),
  yaxt = "n",
  xlab = "Estimate of eta",
  ylab = "",
  main = "Leave-One-Country-Out Robustness for Eta"
)
segments(plot_df$lower, seq_len(nrow(plot_df)), plot_df$upper, seq_len(nrow(plot_df)), lwd = 2)
points(plot_df$estimate, seq_len(nrow(plot_df)), pch = 19, cex = 1.3)
abline(v = 0, lty = 2, col = "gray50")
axis(2, at = seq_len(nrow(plot_df)), labels = plot_df$label, las = 1)
dev.off()

notes_lines <- c(
  "# Leave-One-Country-Out Notes",
  "",
  "This file is generated by `cost_side/cost_reg_leave_one_country_out.R`.",
  "",
  "## Sample",
  "",
  "- The script starts from `cost_side_panel.csv`, the canonical domestic panel.",
  "- Each omission removes observations whose `pcOth1_code1` equals the named country.",
  "- Omitted countries are generated dynamically from every primary source country observed in the baseline regression frame.",
  "",
  "## Specifications",
  "",
  "- The coefficient CSV reports the baseline pass-through coefficient in levels and first differences.",
  "- The PNG plot visualizes the levels estimate with a normal-approximation 95 percent interval.",
  "",
  "## Output Files",
  "",
  "- `leave_one_country_out_coefficients.csv`",
  "- `leave_one_country_out_sample_counts.csv`",
  "- `leave_one_country_out_eta.png`"
)
writeLines(notes_lines, file.path(out_dir, "leave_one_country_out_notes.md"))

cat("Saved:\n")
cat(" -", file.path(out_dir, "leave_one_country_out_coefficients.csv"), "\n")
cat(" -", file.path(out_dir, "leave_one_country_out_sample_counts.csv"), "\n")
cat(" -", file.path(out_dir, "leave_one_country_out_eta.png"), "\n")
