source("cost_side/robustness_helpers.R")

out_dir <- ensure_outputs_dir()
panel <- load_cost_panel("cost_side_panel.csv")
df <- build_regression_frame(panel, include_elasticities = FALSE) %>%
  filter(!is.na(pcOth1_pct1_lag1))

fd <- build_fd_frame(df, keep_cols = c("pcOth1_pct1_lag1"))

median_exposure <- median(fd$pcOth1_pct1_lag1, na.rm = TRUE)
fd <- fd %>%
  mutate(
    exposure_group = ifelse(pcOth1_pct1_lag1 >= median_exposure, "High exposure", "Low exposure")
  )

resid_y_model <- feols(
  ln_costs ~ ln_size + ln_weight + ln_hp + ln_mpg | year,
  data = fd
)
resid_x_model <- feols(
  ln_inv_rer_code1 ~ ln_size + ln_weight + ln_hp + ln_mpg | year,
  data = fd
)

fd <- fd %>%
  mutate(
    resid_d_ln_costs = resid(resid_y_model),
    resid_d_ln_inv_rer = resid(resid_x_model)
  )

make_bins <- function(data, group_name, bins = 8L) {
  group_df <- data %>% filter(exposure_group == group_name)
  probs <- seq(0, 1, length.out = bins + 1L)
  breaks <- unique(quantile(group_df$resid_d_ln_inv_rer, probs = probs, na.rm = TRUE))
  if (length(breaks) < 3L) {
    return(data.frame())
  }
  group_df %>%
    mutate(bin = cut(resid_d_ln_inv_rer, breaks = breaks, include.lowest = TRUE, labels = FALSE)) %>%
    filter(!is.na(bin)) %>%
    group_by(exposure_group, bin) %>%
    summarise(
      mean_resid_d_ln_inv_rer = mean(resid_d_ln_inv_rer, na.rm = TRUE),
      mean_resid_d_ln_costs = mean(resid_d_ln_costs, na.rm = TRUE),
      n = n(),
      .groups = "drop"
    )
}

binned <- bind_rows(
  make_bins(fd, "Low exposure"),
  make_bins(fd, "High exposure")
)

write.csv(
  binned,
  file.path(out_dir, "cost_reduced_form_binned.csv"),
  row.names = FALSE
)

line_cols <- c("Low exposure" = "#1b9e77", "High exposure" = "#d95f02")

png(
  filename = file.path(out_dir, "cost_reduced_form_fx.png"),
  width = 1000,
  height = 700,
  res = 120
)
plot(
  NA, NA,
  xlim = range(binned$mean_resid_d_ln_inv_rer, na.rm = TRUE),
  ylim = range(binned$mean_resid_d_ln_costs, na.rm = TRUE),
  xlab = "Residualized delta log(RER)",
  ylab = "Residualized delta log(cost)",
  main = "Reduced-Form Cost Pattern by Imported-Parts Exposure"
)
abline(h = 0, v = 0, lty = 2, col = "gray60")
for (group_name in names(line_cols)) {
  group_df <- binned %>%
    filter(exposure_group == group_name) %>%
    arrange(mean_resid_d_ln_inv_rer)
  lines(
    group_df$mean_resid_d_ln_inv_rer,
    group_df$mean_resid_d_ln_costs,
    type = "b",
    pch = 19,
    lwd = 2,
    col = line_cols[[group_name]]
  )
}
legend(
  "topleft",
  legend = names(line_cols),
  col = unname(line_cols),
  pch = 19,
  lwd = 2,
  bty = "n"
)
dev.off()

notes_lines <- c(
  "# Reduced-Form Figure Notes",
  "",
  "This file is generated by `cost_side/plot_cost_reduced_form.R`.",
  "",
  "## Construction",
  "",
  "- Start from the canonical domestic panel `cost_side_panel.csv`.",
  "- Build first differences for log costs, log real exchange rates, and vehicle controls.",
  "- Residualize both axes on differenced controls and year fixed effects.",
  paste0("- Split the sample at the median lagged imported-parts exposure: ", sprintf("%.4f", median_exposure), "."),
  "- Bin the residualized exchange-rate shock into eight quantile bins within each exposure group.",
  "",
  "## Output Files",
  "",
  "- `cost_reduced_form_binned.csv`",
  "- `cost_reduced_form_fx.png`"
)
writeLines(notes_lines, file.path(out_dir, "cost_reduced_form_notes.md"))

cat("Saved:\n")
cat(" -", file.path(out_dir, "cost_reduced_form_binned.csv"), "\n")
cat(" -", file.path(out_dir, "cost_reduced_form_fx.png"), "\n")
